version: '3'

services:
  client:
    image: react-app
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - api
    networks: 
      - checklist-mern
  api:
    image: node-app
    ports:
      - 3001:3001
    depends_on:
      - mongo
    networks: 
      - checklist-mern
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks: 
      - checklist-mern
    volumes:
      - mongo-data:/MongoDB/data/db

networks:
  checklist-mern:
    driver: bridge

volumes:
  mongo-data:
    driver: local

