version: '3'

services:
  client:
    image: client-local
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    stdin_open: true
    depends_on:
      - api
    networks: 
      - checklist-mern
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    
  api:
    image: api-local
    ports:
      - 3001:3001
    depends_on:
      - mongo
    networks: 
      - checklist-mern
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks: 
      - checklist-mern
    volumes:
      - mongo-data:/MongoDB/data/db

networks:
  checklist-mern:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local

